### ISSUE TITLE
Player error

### ISSUE THREAD

**Issue by Matthewus** [james-fray/YouTube-No-Buffer#15]
Hi!

As of today the YouTube player throws an error and the video playback is not possible with the add-on enabled.

Browser: Firefox 74

**Comment by james-fray** [comment]
I am not able to reproduce. Do you get any relevant errors on the browser console?

**Comment by Matthewus** [comment]
Unfortunately no. If i disable the add-on, the videos play normally.

Edit:
After some investigation i noticed the following:
I use Enhancer for YouTube + YouTube No Buffer + uBlock Origin.

- If i have all 3 enabled the videos won't play
- If i disable YouTube No Buffer the videos play (other 2 enabled)
- If i disable uBlock Origin the videos play (other 2 enabled)

It looks like the execution order of these add-ons causing the problem.

**Comment by tberghuis** [comment]
can confirm, i'm using extension with chrome and ublock origin. If I disable either ublock or no-buffer video will work.

**Comment by Drewcifer13** [comment]
Can confirm. Was working one minute, then getting error codes the next. If I turn it and only it off (not adblock or ublock origin) the videos play normally without issues/errors.

**Comment by RadioactiveLobster** [comment]
I also use Enhancer for YouTube, YouTube No Buffer and uBlock Origin just like Matthewus and can confirm the same as him.

There is some conflict happening that wasn't there before.

**Comment by james-fray** [comment]
There is a new rule on EasyList to prevent the player from fetching video data when the page is loaded. This probably prevents the player from also fetching advertisements. Anyhow there is no way to bypass this rule. 

You have two options:
1. Whitelist the rule manually from your adblocker options page
2. Update this extension to 0.3.0 release which pauses videos instead of stopping them by default (there is an option to revert in case somebody wants the actually no-buffering behavior)

**Comment by Mansarde** [comment]
For anyone using the AdGuard extension for Chrome:

1. Update YouTube-No-Buffer (if not already)
2. Disable "Pause the player instead of stopping it" in the options
3. Add this AdGuard rule:
@@||youtube.com/get_video_info$domain=youtube.com

This way YT videos will not buffer (because of step 2) and remain playable (because of step 3).
I.e. just like before it will show the thumbnail instead of buffering and only start when you click on it.

**Comment by RadioactiveLobster** [comment]
Any idea on the proper formatting for whitelisting this rule on uBlock Origin, can't seem to figure it out.

**Comment by St0RM53** [comment]
Yes same issue here, i found this syntax here but not very helpful:
https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site

edit: adding this seems to work:

> *youtube.com/get_video_info

edit2: doesn't seem to work reliably though

**Comment by james-fray** [comment]
In my filters section add
```
@@||www.youtube.com/get_video_info$xhr,domain=www.youtube.com
```

**Comment by St0RM53** [comment]
Both @james-fray and @Mansarde 's filters under the filter section work, but the extension still doesn't seem to block pre-buffering reliably. It works 60% of the time.

It's a big clusterfuck:
https://github.com/easylist/easylist/issues/5112

**Comment by james-fray** [comment]
@St0RM53 can you give the latest commit a try and let me know how it works? Are you familiar with dev installation?

**Comment by St0RM53** [comment]
@james-fray Just tested it. I'm not sure what changes you've made but the stop function works as expected. However you still need to whitelist get_video_info otherwise you will get playback error. However the filter(s) happens to work reliably now (which i'm assuming this is what you've fixed).

I only tested the following filter though:

`@@||www.youtube.com/get_video_info$xhr,domain=www.youtube.com`
